version: "3.9"
services:
  db:
    image: postgres:16
    container_name: colearn_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: colearn
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d colearn"]
      interval: 5s
      timeout: 3s
      retries: 10
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ken.java@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
  # app:
  #   build: .
  #   image: colearn-api:latest
  #   environment:
  #     NODE_ENV: production
  #     DATABASE_URL: ${DATABASE_URL}
  #     JWT_SECRET: ${JWT_SECRET}
  #   depends_on:
  #     - db
  #   networks: [ web ]
  #   ports:
  #     - "3000:3000"
volumes:
  pgdata_dev:
